title: Shenee Norton
#logo: /assets/img/profilePic-1.jpg
description: Data Analytics | Business Intelligence | Applied Statistics | Python & SQL
#show_downloads: true
github:
  is_project_page: false
theme: jekyll-theme-minimal
